python setup.cgi -u user1 -p user1
python setup.cgi -u user2 -p user2
python setup.cgi -u user3 -p user3
python setup.cgi -u user4 -p user4
python setup.cgi -u user5 -p user5
python setup.cgi -u user6 -p user6
python setup.cgi -u user7 -p user7
python setup.cgi -u user8 -p user8
python setup.cgi -u user9 -p user9
python setup.cgi -u user10 -p user10
python setup.cgi -u user11 -p user11
python setup.cgi -u user12 -p user12
python setup.cgi -u user13 -p user13
python setup.cgi -u user14 -p user14
python setup.cgi -u user15 -p user15
python setup.cgi -u user16 -p user16
python setup.cgi -u user17 -p user17
python setup.cgi -u user18 -p user18
python setup.cgi -u user19 -p user19
python setup.cgi -u user20 -p user20
python setup.cgi -u user21 -p user21
python setup.cgi -u user22 -p user22
python setup.cgi -u user23 -p user23
python setup.cgi -u user24 -p user24
python setup.cgi -u user25 -p user25
python setup.cgi -u user26 -p user26
python setup.cgi -u user27 -p user27
python setup.cgi -u user28 -p user28
python setup.cgi -u user29 -p user29
python setup.cgi -u user30 -p user30
